package com.lowdragmc.photon.gui.editor;

import com.lowdragmc.lowdraglib.utils.LocalizationUtils;

import java.util.Map;

/**
 * Keeps Photon editor labels readable even when a modpack resource pack or
 * older LDLib path does not resolve Photon's translation keys in configurators.
 */
public final class PhotonLocalization {
    private static final Map<String, String> ZH_CN_FALLBACKS = Map.ofEntries(
            Map.entry("photon.gui.editor.config.name", "名称"),
            Map.entry("photon.gui.editor.config.transform", "变换"),
            Map.entry("photon.gui.editor.config.duration", "持续时间"),
            Map.entry("photon.gui.editor.config.looping", "循环"),
            Map.entry("photon.gui.editor.config.start_delay", "开始延迟"),
            Map.entry("photon.gui.editor.config.start_lifetime", "初始生命周期"),
            Map.entry("photon.gui.editor.config.start_speed", "初始速度"),
            Map.entry("photon.gui.editor.config.start_size", "初始大小"),
            Map.entry("photon.gui.editor.config.start_rotation", "初始旋转"),
            Map.entry("photon.gui.editor.config.start_color", "初始颜色"),
            Map.entry("photon.gui.editor.config.simulation_space", "模拟空间"),
            Map.entry("photon.gui.editor.config.max_particles", "最大粒子数"),
            Map.entry("photon.gui.editor.config.parallel_update", "并行更新"),
            Map.entry("photon.gui.editor.config.parallel_rendering", "并行渲染"),
            Map.entry("photon.gui.editor.config.emission", "发射"),
            Map.entry("photon.gui.editor.config.shape", "形状"),
            Map.entry("photon.gui.editor.config.material", "材质"),
            Map.entry("photon.gui.editor.config.renderer", "渲染器"),
            Map.entry("photon.gui.editor.config.physics", "物理"),
            Map.entry("photon.gui.editor.config.fixed_light", "固定光照"),
            Map.entry("photon.gui.editor.config.velocity_over_lifetime", "生命周期速度"),
            Map.entry("photon.gui.editor.config.inherit_velocity", "继承速度"),
            Map.entry("photon.gui.editor.config.lifetime_by_emitter_speed", "按发射器速度调整寿命"),
            Map.entry("photon.gui.editor.config.force_over_lifetime", "生命周期受力"),
            Map.entry("photon.gui.editor.config.color_over_lifetime", "生命周期颜色"),
            Map.entry("photon.gui.editor.config.color_by_speed", "按速度变色"),
            Map.entry("photon.gui.editor.config.size_over_lifetime", "生命周期大小"),
            Map.entry("photon.gui.editor.config.size_by_speed", "按速度缩放"),
            Map.entry("photon.gui.editor.config.rotation_over_lifetime", "生命周期旋转"),
            Map.entry("photon.gui.editor.config.rotation_by_speed", "按速度旋转"),
            Map.entry("photon.gui.editor.config.noise", "噪声"),
            Map.entry("photon.gui.editor.config.uv_animation", "UV 动画"),
            Map.entry("photon.gui.editor.config.trails", "拖尾"),
            Map.entry("photon.gui.editor.config.sub_emitters", "子发射器"),
            Map.entry("photon.gui.editor.config.end", "终点"),
            Map.entry("photon.gui.editor.config.width", "宽度"),
            Map.entry("photon.gui.editor.config.emit_rate", "发射速率"),
            Map.entry("photon.gui.editor.config.color", "颜色"),
            Map.entry("photon.gui.editor.config.time", "时间"),
            Map.entry("photon.gui.editor.config.min_vertex_distance", "最小顶点距离"),
            Map.entry("photon.gui.editor.config.smooth_interpolation", "平滑插值"),
            Map.entry("photon.gui.editor.config.uv_mode", "UV 模式"),
            Map.entry("photon.gui.editor.config.width_over_trail", "拖尾宽度"),
            Map.entry("photon.gui.editor.config.color_over_trail", "拖尾颜色"),
            Map.entry("photon.gui.editor.config.emission_rate", "发射速率"),
            Map.entry("photon.gui.editor.config.emission_mode", "发射模式"),
            Map.entry("photon.gui.editor.config.bursts", "爆发"),
            Map.entry("photon.gui.editor.config.burst", "爆发"),
            Map.entry("photon.gui.editor.config.count", "数量"),
            Map.entry("photon.gui.editor.config.cycles", "循环次数"),
            Map.entry("photon.gui.editor.config.interval", "间隔"),
            Map.entry("photon.gui.editor.config.probability", "概率"),
            Map.entry("photon.gui.editor.config.position", "位置"),
            Map.entry("photon.gui.editor.config.rotation", "旋转"),
            Map.entry("photon.gui.editor.config.scale", "缩放"),
            Map.entry("photon.gui.editor.config.blend_mode", "混合模式"),
            Map.entry("photon.gui.editor.config.cull", "剔除"),
            Map.entry("photon.gui.editor.config.depth_test", "深度测试"),
            Map.entry("photon.gui.editor.config.depth_mask", "深度写入"),
            Map.entry("photon.gui.editor.config.layer", "图层"),
            Map.entry("photon.gui.editor.config.bloom_effect", "泛光效果"),
            Map.entry("photon.gui.editor.config.bloom_color", "泛光颜色"),
            Map.entry("photon.gui.editor.config.from", "起点"),
            Map.entry("photon.gui.editor.config.to", "终点"),
            Map.entry("photon.gui.editor.config.render_mode", "渲染模式"),
            Map.entry("photon.gui.editor.config.shade", "明暗"),
            Map.entry("photon.gui.editor.config.use_block_uv", "使用方块 UV"),
            Map.entry("photon.gui.editor.config.has_collision", "启用碰撞"),
            Map.entry("photon.gui.editor.config.removed_when_collided", "碰撞后移除"),
            Map.entry("photon.gui.editor.config.friction", "摩擦"),
            Map.entry("photon.gui.editor.config.gravity", "重力"),
            Map.entry("photon.gui.editor.config.bounce_chance", "反弹概率"),
            Map.entry("photon.gui.editor.config.bounce_rate", "反弹倍率"),
            Map.entry("photon.gui.editor.config.bounce_spread_rate", "反弹扩散倍率"),
            Map.entry("photon.gui.editor.config.emitter", "发射器"),
            Map.entry("photon.gui.editor.config.mesh", "网格"),
            Map.entry("photon.gui.editor.config.speed_range", "速度范围"),
            Map.entry("photon.gui.editor.config.force", "力"),
            Map.entry("photon.gui.editor.config.mode", "模式"),
            Map.entry("photon.gui.editor.config.multiply", "乘算"),
            Map.entry("photon.gui.editor.config.multiplier", "倍率"),
            Map.entry("photon.gui.editor.config.sky_light", "天空光照"),
            Map.entry("photon.gui.editor.config.block_light", "方块光照"),
            Map.entry("photon.gui.editor.config.frequency", "频率"),
            Map.entry("photon.gui.editor.config.quality", "质量"),
            Map.entry("photon.gui.editor.config.remap", "重映射"),
            Map.entry("photon.gui.editor.config.size", "大小"),
            Map.entry("photon.gui.editor.config.remap_curve", "重映射曲线"),
            Map.entry("photon.gui.editor.config.roll", "翻滚"),
            Map.entry("photon.gui.editor.config.pitch", "俯仰"),
            Map.entry("photon.gui.editor.config.yaw", "偏航"),
            Map.entry("photon.gui.editor.config.linear", "线性"),
            Map.entry("photon.gui.editor.config.orbital_mode", "轨道模式"),
            Map.entry("photon.gui.editor.config.orbital", "轨道"),
            Map.entry("photon.gui.editor.config.offset", "偏移"),
            Map.entry("photon.gui.editor.config.speed_modifier", "速度修正"),
            Map.entry("photon.gui.editor.config.tiles", "分块"),
            Map.entry("photon.gui.editor.config.animation", "动画"),
            Map.entry("photon.gui.editor.config.frame_over_time", "随时间帧"),
            Map.entry("photon.gui.editor.config.start_frame", "起始帧"),
            Map.entry("photon.gui.editor.config.cycle", "周期"),
            Map.entry("photon.gui.editor.config.ratio", "比例"),
            Map.entry("photon.gui.editor.config.lifetime", "生命周期"),
            Map.entry("photon.gui.editor.config.die_with_particles", "随粒子消失"),
            Map.entry("photon.gui.editor.config.size_affects_width", "大小影响宽度"),
            Map.entry("photon.gui.editor.config.size_affects_lifetime", "大小影响生命周期"),
            Map.entry("photon.gui.editor.config.inherit_particle_color", "继承粒子颜色"),
            Map.entry("photon.gui.editor.config.emitters", "发射器"),
            Map.entry("photon.gui.editor.config.event", "事件"),
            Map.entry("photon.gui.editor.config.emit_probability", "发射概率"),
            Map.entry("photon.gui.editor.config.tick_interval", "刻间隔"),
            Map.entry("photon.gui.editor.config.inherit_color", "继承颜色"),
            Map.entry("photon.gui.editor.config.inherit_size", "继承大小"),
            Map.entry("photon.gui.editor.config.inherit_rotation", "继承旋转"),
            Map.entry("photon.gui.editor.config.inherit_lifetime", "继承生命周期"),
            Map.entry("photon.gui.editor.config.inherit_duration", "继承持续时间"),
            Map.entry("photon.gui.editor.config.enable_blend", "启用混合"),
            Map.entry("photon.gui.editor.config.src_color_factor", "源颜色因子"),
            Map.entry("photon.gui.editor.config.dst_color_factor", "目标颜色因子"),
            Map.entry("photon.gui.editor.config.src_alpha_factor", "源透明因子"),
            Map.entry("photon.gui.editor.config.dst_alpha_factor", "目标透明因子"),
            Map.entry("photon.gui.editor.config.blend_func", "混合函数"),
            Map.entry("photon.gui.editor.config.texture", "贴图"),
            Map.entry("photon.gui.editor.config.discard_threshold", "丢弃阈值"),
            Map.entry("photon.gui.editor.config.shader", "着色器"),
            Map.entry("photon.gui.editor.config.emit_from", "发射来源"),
            Map.entry("photon.gui.editor.config.radius", "半径"),
            Map.entry("photon.gui.editor.config.radius_thickness", "半径厚度"),
            Map.entry("photon.gui.editor.config.arc", "弧度"),
            Map.entry("photon.gui.editor.config.angle", "角度"),
            Map.entry("photon.gui.editor.config.x", "X"),
            Map.entry("photon.gui.editor.config.y", "Y"),
            Map.entry("photon.gui.editor.config.z", "Z"),
            Map.entry("photon.gui.editor.config.speed_x", "X 速度"),
            Map.entry("photon.gui.editor.config.speed_y", "Y 速度"),
            Map.entry("photon.gui.editor.config.speed_z", "Z 速度"),
            Map.entry("photon.gui.editor.config.type", "类型"),
            Map.entry("photon.gui.editor.number_function.all_in_one", "合并控制"),
            Map.entry("photon.gui.editor.number_function.separate_axes", "分轴控制"),
            Map.entry("All in one", "合并控制"),
            Map.entry("Separate Axes", "分轴控制"),
            Map.entry("startLifetime", "初始生命周期"),
            Map.entry("startSpeed", "初始速度"),
            Map.entry("startSize", "初始大小"),
            Map.entry("startRotation", "初始旋转"),
            Map.entry("startColor", "初始颜色"),
            Map.entry("simulationSpace", "模拟空间"),
            Map.entry("maxParticles", "最大粒子数"),
            Map.entry("parallelUpdate", "并行更新"),
            Map.entry("parallelRendering", "并行渲染"),
            Map.entry("Emission", "发射"),
            Map.entry("Shape", "形状")
    );

    private PhotonLocalization() {
    }

    public static String format(String key) {
        var translated = LocalizationUtils.format(key);
        if (!translated.equals(key)) {
            return translated;
        }
        return ZH_CN_FALLBACKS.getOrDefault(key, key);
    }
}
